name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonbit-community/setup-moonbit@main
      - run: moon check --diagnostic-limit 10

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonbit-community/setup-moonbit@main
      - run: moon test --diagnostic-limit 10
