name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonbit-community/setup-moonbit@main
      - run: moon update
      - run: moon check --diagnostic-limit 10

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonbit-community/setup-moonbit@main
      - run: moon update
      - run: >
          moon test
          --package tonyfettes/epoxy/internal/glinfo
          --package tonyfettes/epoxy-generator/gen
          --package tonyfettes/epoxy-generator/cdecl
          --package tonyfettes/epoxy-generator/aliasgroup
          --diagnostic-limit 10
